config/routes.rb
Rails.application.routes.draw do

  resources :programs
  devise_for :users 

  get '/dashboard', :to => 'dashboard#index' 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'programs#index' 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :users
  mount_uploader :form, FormUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :role
  after_initialize :set_default_role
  has_many :programs

  def set_default_role
    self.role ||= "Applicant"
  end


end

app/controllers/RegistrationsController.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?
                                            
  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :username)}
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected                                                  

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_in_path_for(resource)

    if resource.is_a?(AdminUser)
      admin_root_path
    else
      dashboard_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @user = User.find(current_user)
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :can_edit?, :except => [:index, :show]
  before_filter :is_admin?, :only => [:new, :create, :destroy]

  def new
    @program = Program.new
  end

  def create
    @program = Program.new(program_params)
    if @program.name == ""
      redirect_to new_program_path
      flash[:notice] = 'New program must have a name'
    else    
      if @program.save
        redirect_to @program, :notice => 'Successfully created a new program!'
      else
        flash[:notice] = 'Failed to create a new program.'
      end
    end
  end

  def update
    @program = Program.find(params[:id])

    if @program.update_attributes(program_params)
      redirect_to @program, :notice => 'Successfully updated a new program!'
    else
      flash[:notice] = 'Failed to update a new program.'
    end
  end

  def edit
    @program = Program.find(params[:id])
  end

  def destroy
    @program = Program.find(params[:id])
    @program.destroy
  end

  def index
    @programs = Program.all
  end

  def show
    @program = Program.find(params[:id])
  end

  private 
  def program_params
    params.require(:program).permit(:name, :start_date, :end_date, :pending, :form_url, :info)
  end
  
  def can_edit?
    if current_user.role != 'Applicant' && current_user.role != 'Reviewer'
      true
    else
      redirect_to programs_path
    end
  end

  def is_admin?
    if current_user.role == 'Admin'
      true
    else
      redirect_to programs_path
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/dashboard/Buttons/_buttons.html.haml
- if @user.role == 'Applicant'
  %div{:class => 'row'}
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Search for Applications
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Submit Application
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} See Application Feedback

- if @user.role == 'Reviewer'
  %div{:class => 'row'}
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Review Applications
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} See Application Feedback
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} See My Programs

- if @user.role == 'Funding Source'
  %div{:class => 'row'}
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Review Applications
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} See Application Feedback
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Approve Applications
  %div{:class => 'row'}
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Upload New Application Form
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} See My Programs

- if @user.role == 'Admin'
  %div{:class => 'row'}
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Search for Applications
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Submit Application
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} See Application Feedback
  %div{:class => 'row'}
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Review Applications
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Approve Applications
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Upload New Application Form
  %div{:class => 'row'}
    %div{:class => 'col-md-4'}
      %button{:class => 'btn btn-large col-md-12', :disabled => "disabled", :type => "button"} Approve New Application Forms
    %div{:class => 'col-md-4'}
      = link_to new_program_path do
        %button{:class => 'btn btn-large col-md-12', :type => "button"} Create New Programs
    %div{:class => 'col-md-4'}
      = link_to programs_path do
        %button{:class => 'btn btn-large col-md-12', :type => "button"} View Programs

app/views/dashboard/index.html.haml
%div{:style => 'margin: 30px'}
  %h1{:style => 'display:inline; margin:15px'}= "Welcome, #{@user.username}"


  = link_to(destroy_user_session_path, :method => :delete) do
    %img{:style => 'float:right; width:20px; height:20px; margin:15px 15px 0px 0px', :src => '/images/logout.png'}
    %div{:style => 'float:right; margin:15px 5px 0px 0px'} Logout

  %div{:class => 'container-fluid', :style => 'margin:30px'}
    = render :partial => "dashboard/Buttons/buttons.html.haml"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grantapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>  

<%= yield %>

</body>
</html>

app/views/programs/_program_form.html.haml
-if @program.errors.any?
  #error_explanation
  %h2
    =pluralize(@program.errors.count, "error")
    prohibited this task from being saved:
    %ul
      -@article.errors.full_messages.each do |msg|
        %li=msg

= label :program, :name, 'Name'
= text_field :program, :name

= label :program, :info, 'Program Info'
= text_area :program, :info

= label :program, :start_date, 'Start Date'
= date_select :program, :start_date

= label :program, :end_date, 'End Date'
= date_select :program, :end_date


= label :program, :form_url, 'Form URL'
= text_field :program, :form_url

= label :program, :pending, 'Status'
= select(:program, :pending, options_for_select([["Active", false],["Pending", true]], @program.pending))
  
%br
= submit_tag 'Submit'

%br
= link_to 'Back to Programs', programs_path
%br
= link_to 'Back to Dashboard', dashboard_path

app/views/programs/create.html.haml
<h1>Programs#create</h1>
<p>Find me in app/views/programs/create.html.erb</p>

app/views/programs/destroy.html.haml
%p Successfully Deleted The Program

%div{:style => 'margin: 30px'}

  %br
  %br

  = link_to 'Back to Dashboard', dashboard_path

app/views/programs/edit.html.haml
%div{:style => 'margin: 30px'}

  =form_for @program do |f|
    =render partial: 'program_form', f: f

  - if current_user.role == 'Admin'
    = link_to 'Delete Program', program_path(@program.id), :method => :delete

app/views/programs/index.html.haml
%div{:style => 'margin: 30px'}
  %h1 Programs

  - @programs.each do |program|
    %h3 
      Program:
      =link_to "#{program.name}", program_path(program.id)
    %p
      %strong Program Info:
      %br
      =program.info
    %p 
      %strong Start Date: 
      =program.start_date
    %p 
      %strong End Date: 
      =program.end_date
    %p
      %strong Status:
      - if program.pending
        Pending
      - else
        Active

  %br

  = link_to 'Back to Dashboard', dashboard_path

app/views/programs/new.html.haml
%div{:style => 'margin: 30px'}

  =form_for @program do |f|
    =render partial: 'program_form', f: f

app/views/programs/show.html.haml
%div{:style => 'margin: 30px'}
  %h1= "Program: #{@program.name}"
  %p
    %strong Program Info:
    %br
    =@program.info
  %p 
    %strong Start Date: 
    =@program.start_date
  %p 
    %strong End Date: 
    =@program.end_date
  %p
    %strong Status: 
    - if @program.pending
      Pending
    - else    
      Active

  - if @program.form_url == nil || @program.form_url.empty?
    %p Form Not Available
  -else
    - if @program.form_url.start_with?('http://','https://')
      = link_to 'View Form', @program.form_url
    - else
      = link_to 'View Form', "http://" + @program.form_url

    %br

  - if current_user != nil && current_user.role != 'Applicant' && current_user.role != 'Reviewer'
    = link_to 'Edit Program', edit_program_path(@program.id)

  %br

  = link_to 'Back to Programs', programs_path
  %br
  = link_to 'Back to Dashboard', dashboard_path

app/views/programs/update.html.haml
<h1>Programs#update</h1>
<p>Find me in app/views/programs/update.html.erb</p>